logging:
    level:
        com:
            etz: debug
        org:
            hibernate:
                sql: debug
            springframework: debug
spring:
    application: 'null'
    datasource:
#        url: jdbc:mysql://172.17.10.16:3306/mpb_db?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
#        password: A123456@qwER1#
#        username: samuel.sawyerr DB DETAILS
        url: jdbc:sqlserver://mpb-verification-db.database.windows.net
        password: bubxI4-kimrus-toxgyw
        username: mpb-db-user

        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


    http:
        multipart:
            enabled: true
    jpa:
#        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
#                dialet: org.hibernate.dialect.MySQL5Dialect
                dialect: org.hibernate.dialect.SQLServer2008Dialect
                format_sql: true
                show_sql: true
                type: trace
        show-sql: true
    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
app:
    security:
        client-id: MPB_PORTAL_CLIENT
        client-secret: password1234
        resource-id: MPB_PORTAL_RESOURCE
        validity:
            access-token: 120
            refresh-token: 24000


server:
    port: 20003