package com.etz.MPB.portal.enums;

public enum DocumentType {
    LIVELINESS_CAPTURE,SELFIE_IMAGE,FINGER_PRINT,QR_CODE,
    VERIFICATION_SLIP,NIN_RETURNED_IMAGE,DL_RETURNED_IMAGE,NIP_RETURNED_IMAGE
}
